[project]
name = "bps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "flytekit>=1.15.0",
    "httpx>=0.28.1",
]
