[project]
name = "bps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "beautifulsoup4>=4.13.3",
  "httpx>=0.28.1",
  "prefect[kubernetes]>=3.2.11",
  "scrapy>=2.12.0",
]
